# Workflows
#   Jobs
#     Steps
name: section3 >> Test & Deploy Project
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd section3
          npm ci

      - name: Run tests
        run: |
          cd section3
          npm test
  
  deploy:
    needs: test # use brackets for multiple
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd section3
          npm ci

      - name: Build project
        run: |
          cd section3
          npm run build

      - name: Deploy
        run: echo "Deploying ..."