name: section3 >> Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd second-action
          npm ci
      - name: Lint
        run: |
          cd second-action
          npm run lint
      - name: Test code
        run: |
          cd second-action
          npm run test
      - name: Build code
        run: |
          cd second-action
          npm run build
      - name: Deploy code
        run: echo "Deploying..."