name: section6 >> Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env: # available in all job unless overridden in job
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    # environment: testing
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.npxxeaz.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd section6
          npm ci
      - name: Run server
        run: |
          cd section6
          npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: |
          cd section6
          npm test
      - name: Output information # there are also default env variables
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
